name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Instalar dependencias
      uses: pip install --no-cache-dir --upgrade -r requirements.txt
      with:
        python-version: 3.9
    - name: Ejecutar el servicio  
      run: uvicorn app.main:app --host 0.0.0.0 --port 8000
      with:
        python-version: 3.